title: Draftlab Scaffold
description: Draftlab Scaffold - Our Web Development Starter
url: https://scaffold.draftlab.org
favicon: /favicon.svg
defaultOgImage: /src/assets/draftlab-seo.png
social:
  twitter: https://twitter.com/yourhandle
  github: https://github.com/yourorg
  linkedin: https://linkedin.com/company/yourcompany
